name: nutrifacts
description: "A diet companion flutter project that displays nutrition facts for different types of food."
publish_to: 'none'
version: 1.0.1+3
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  fl_chart: ^0.66.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  loading_indicator: ^3.1.1
  connectivity_plus: ^2.3.8
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.6.2

flutter_launcher_icons:
  image_path: "assets/images/app_logo.jpg"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  linux:
    generate: true
  macos:
    generate: true

flutter:
  uses-material-design: true
  fonts:
    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf
  assets:
    - assets/sample_api_responses/sample_food_list_edamam_response.json
